// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1tgUNz0-iqYgVmcUsR6KKdHPd3YywOcw',
    appId: '1:489943701160:web:d6f0f0a6560b836ba3d49d',
    messagingSenderId: '489943701160',
    projectId: 'OnwaPay-640a7',
    authDomain: 'OnwaPay-640a7.firebaseapp.com',
    storageBucket: 'OnwaPay-640a7.firebasestorage.app',
    measurementId: 'G-J5KS9K1X34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKE9uJtMdJTMFabc3Y1qDNYlYozquF9QE',
    appId: '1:489943701160:android:4490b0a1dbfda73ba3d49d',
    messagingSenderId: '489943701160',
    projectId: 'OnwaPay-640a7',
    storageBucket: 'OnwaPay-640a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuvOBDkIB9fWgbLwVPfVIfvU7p52t_mE',
    appId: '1:489943701160:ios:cc6df517daa3e234a3d49d',
    messagingSenderId: '489943701160',
    projectId: 'OnwaPay-640a7',
    storageBucket: 'OnwaPay-640a7.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChuvOBDkIB9fWgbLwVPfVIfvU7p52t_mE',
    appId: '1:489943701160:ios:cc6df517daa3e234a3d49d',
    messagingSenderId: '489943701160',
    projectId: 'OnwaPay-640a7',
    storageBucket: 'OnwaPay-640a7.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1tgUNz0-iqYgVmcUsR6KKdHPd3YywOcw',
    appId: '1:489943701160:web:458ad9b361bdc20ba3d49d',
    messagingSenderId: '489943701160',
    projectId: 'OnwaPay-640a7',
    authDomain: 'OnwaPay-640a7.firebaseapp.com',
    storageBucket: 'OnwaPay-640a7.firebasestorage.app',
    measurementId: 'G-TC3WXDB274',
  );
}
