const Map<String, Map<String, String>> lang = {
  'en': {
    'appName': 'OnwaPay',
    'availableBalance': 'Available balance',
    'addFunds': 'Add funds',
    'buyAirtime': 'Buy airtime',
    'sendFunds': 'Send funds',
    'buyBundle': 'Buy a bundle',
    'paySchoolFees': 'Pay School Fees',
    'payBills': 'Pay Bills',
    'transactions': 'Transactions',
    'recentTransactions': 'Recent Transactions',
    'noRecentTransactions': 'No recent transactions',
    'changeLanguage': 'Change Language',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'support': 'Support',
    'about': 'About',
    'logout': 'Logout',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
  },
  'fr': {
    'appName': 'OnwaPay',
    'availableBalance': 'Solde disponible',
    'addFunds': 'Ajouter des fonds',
    'buyAirtime': 'Acheter du crédit',
    'sendFunds': 'Envoyer de l\'argent',
    'buyBundle': 'Acheter un forfait',
    'paySchoolFees': 'Payer les frais scolaires',
    'payBills': 'Payer les factures',
    'transactions': 'Transactions',
    'recentTransactions': 'Transactions récentes',
    'noRecentTransactions': 'Aucune transaction récente',
    'changeLanguage': 'Changer la langue',
    'settings': 'Paramètres',
    'notifications': 'Notifications',
    'support': 'Assistance',
    'about': 'À propos',
    'logout': 'Se déconnecter',
    'darkMode': 'Mode sombre',
    'lightMode': 'Mode clair',
  },
};
